id: a9cd4c2fb89e4d58a052004c1b4650bd
initial_creation_type: ocr
source_metadata:
  volumes:
    cfeb0c0a3a234800bc8b72dcbf4d3f4d:
      base_file: v060.txt
      image_group_id: I1PD95906
      title: ''
      total_pages: 1877
      volume_number: 61
